# This file contains screen compatibility bindings

# Prefix
set -g prefix C-b
bind C-b send-prefix

# C-B C-B movement
bind-key C-b last-window

# Beginning of the line
bind a send-prefix

# Commands
set -g command-alias[0] quit='kill-session'
set -g command-alias[1] help='list-commands'

