ARG SYSTEM=debian:trixie
FROM $SYSTEM

RUN apt-get update && apt-get install -y sudo which passwd
RUN useradd -m -s /bin/bash shelluser \
    && echo 'shelluser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/shelluser

COPY . /home/shelluser/.config/ShellRc
RUN chown -R shelluser:shelluser /home/shelluser/.config

ENV SHELL=/bin/bash
USER shelluser
WORKDIR /home/shelluser
ENTRYPOINT ["/home/shelluser/.config/ShellRc/docker/entrypoint.sh"]

