#!/usr/bin/env python3
import sys
from pathlib import Path

user_zdotdir = Path(__file__).absolute().parent / "zdotdir"
if len(sys.argv) < 2:
    print("Usage: install-zdotdir.py <username>", file=sys.stderr)
    sys.exit(1)
username = sys.argv[1]

script = f"""
# generated by ShellRc for {username}
if [[ "$USER" == "{username}" ]]; then
    export ZDOTDIR="{user_zdotdir}"
fi
"""

zshenv_file = Path("/etc/zsh/zshenv")
zshenv_file.parent.mkdir(parents=True, exist_ok=True)
zshenv_file.touch(exist_ok=True)
text = zshenv_file.read_text()

if not script in text:
    with open(zshenv_file, "a") as out:
        print(script, file=out)

