#!/usr/bin/env python3
import os
import sys
from pathlib import Path

user_zdotdir = Path(__file__).absolute().parent / "zshenv"

script = f"""
# generated by ShellRc for {os.getlogin()}
if [[ "$USER" == "{os.getlogin()}" ]]; then
    export ZDOTDIR="{user_zdotdir}"
fi
"""

zshenv_file = Path("/etc/zsh/zshenv")
text = zshenv_file.read_text()

if not script in text:
    with open(zshenv_file, "a") as out:
        print(script, file=out)

