#!/usr/bin/env python3
import os
import pwd
import sys
from pathlib import Path

user_zdotdir = Path(__file__).absolute().parent / "zdotdir"
username = pwd.getpwuid(os.getuid()).pw_name

script = f"""
# generated by ShellRc for {username}
if [[ "$USER" == "{username}" ]]; then
    export ZDOTDIR="{user_zdotdir}"
fi
"""

zshenv_file = Path("/etc/zsh/zshenv")
zshenv_file.parent.mkdir(parents=True, exist_ok=True)
zshenv_file.touch(exist_ok=True)
text = zshenv_file.read_text()

if not script in text:
    with open(zshenv_file, "a") as out:
        print(script, file=out)

